### ISSUE TITLE
Docker Compose for using existing DB

### ISSUE THREAD

**Issue by manik-chopra** [gianniceresa/docker-images#1]
Hi there,

This has been extremely useful and we are able to run OBIEE 12c docker in minutes thus thanks to you for putting it out there. 

Is there a way for you to share if instead of building DB layer from scratch we can connect to existing database by changing docker compose.yml file?

again thanks in advance!

**Comment by gianniceresa** [comment]
Hi,
Good to know it was useful for you.
Why don't you take the normal docker image?
If you take this one https://github.com/gianniceresa/docker-images/tree/master/OracleBIEE it's just that: OBIEE alone without dependencies. You can provide the parameters you need like the DB connection string for the RCU, the DB sys account and password as variable when running the container.

**Comment by manik-chopra** [comment]
Thanks, everything looks good but do you know how to supply user id for DB user for which password is provide thru BI_CONFIG_RCU_PWD or it always expect to connect as sysdba ?

**Comment by gianniceresa** [comment]
In the README page it is written: https://github.com/gianniceresa/docker-images/tree/master/OracleBIEE#available-variables

BI_CONFIG_RCU_USER: by default "sys". The installer require this user to have sysdba privileges, that's the RCU.

**Comment by manik-chopra** [comment]
Hi again, this worked perfectly and I have an OBIEE 12c only image that connects to 11g database (without container). There are one thing i'm still unable to achieve, let me know if you can shed some light. 

**Committing container changes to image so that image can be moved around to another host (connecting to same database and schema). I tried docker container commit to create new image from existing first container however the OBIEE fails to start in the container created from new image.** Its getting following error - 
_Failed to start one or more Servers
NodeManager (87a308292616:9506): NOT RUNNING
Please start node manager and re-run this command to obtain complete status_

As we will make changes to OBIEE dashboard, I'll need a way to commit changes back to image and redeploy image to any host and bring up container connecting to same schema/db that was created initially during first time setup. 

Let me know your thoughts and thanks again for help!

**Comment by gianniceresa** [comment]
That's not how OBIEE work. The RCU schemas are exclusively single use: one instance and that single one can use it.
If the changes you talk about are OBIEE related (RPD, catalog) you must manage them as normal OBIEE, deploying them on the new container.
You can customize the container to add a step in the start script: after configuring OBIEE it also deploy your custom RPD and catalog and so you get a customized OBIEE. For example I have an image which deploy a custom style and set it as default, all I did was adding the few steps for that in the runOBIEE.sh script.
Docker isn't supposed to abuse how OBIEE works. If you got an error on node manager not running you need to apply the usual debug steps: look at logs, connect to the container and start looking around at the root cause.

**Comment by manik-chopra** [comment]
Hi again,

We were able to achieve setting up OBIEE on new container with new RCU each time. Also, we automated the process to import the RPDs, web catalog etc. from source that we have been using. 
However, we are unable to import the user access & settings. As you have so much knowledge about OBIEE, do you know how to export/import user settings/access to the containerized OBIEE environment. 

We don't want to manually do user access every time we setup new OBIEE env. 

thanks for help again.

-m

**Comment by gianniceresa** [comment]
Hi,
So we all agree there isn't an issue with the docker image. For what you are asking you maybe want to read about the BAR file which is used in 12c to move content around packaging multiple pieces (based on config) in a single file which can then me imported in another environment. More in general if you google the topic on how to export/import security in OBIEE you find quite a lot of answers.
Being a pure OBIEE question GitHub isn't the place to address that kind of topic, you maybe want to visit the OTN forum (https://community.oracle.com) if you still can't find your answer online.

**Comment by manik-chopra** [comment]
Thanks Gianni, we have already tried bar file, and weblogic import/export. None of these seems to get us the users in weblogic we need. thanks.
