### ISSUE TITLE
OBIEE docker container start, fails to start Adminserver

### ISSUE THREAD

**Issue by manik-chopra** [gianniceresa/docker-images#2]
Hi,

We are having problem starting a stopped container. Below are the logs during start and this is the pure vanilla OBIEE container with no customization. Any help would be appreciated on why the restart of the container after being stopped is not working. thanks

Starting OBIEE
Starting domain; Using domainHome: /opt/oracle/config/domains/bi ...

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

<Aug 15, 2017 1:01:39 AM UTC> <Info> <Security> <BEA-090905> <Disabling the CryptoJ JCE Provider self-integrity check for better startup performance. To enable this check, specify -Dweblogic.security.allowCryptoJDefaultJCEVerification=true.>
<Aug 15, 2017 1:01:39 AM UTC> <Info> <Security> <BEA-090906> <Changing the default Random Number Generator in RSA CryptoJ from ECDRBG128 to HMACDRBG. To disable this change, specify -Dweblogic.security.allowCryptoJDefaultPRNG=true.>
<Aug 15, 2017 1:01:40 AM UTC> <Info> <Security> <BEA-090909> <Using the configured custom SSL Hostname Verifier implementation: weblogic.security.utils.SSLWLSHostnameVerifier$NullHostnameVerifier.>
Node manager not running. Starting it...
NMProcess: NODEMGR_HOME is already set to /opt/oracle/config/domains/bi/nodemanager
NMProcess: CLASSPATH=/usr/java/jdk1.8.0_101/lib/tools.jar:/opt/oracle/product/12.2.1.2.0/wlserver/server/lib/weblogic.jar:/opt/oracle/product/12.2.1.2.0/wlserver/../oracle_common/modules/net.sf.antcontrib_1.1.0.0_1-0b3/lib/ant-contrib.jar:/opt/oracle/product/12.2.1.2.0/wlserver/modules/features/oracle.wls.common.nodemanager.jar::/usr/java/jdk1.8.0_101/lib/tools.jar:/opt/oracle/product/12.2.1.2.0/wlserver/modules/features/wlst.wls.classpath.jar:/opt/oracle/product/12.2.1.2.0/wlserver/..
NMProcess: + /usr/java/jdk1.8.0_101/bin/java -server -Xms32m -Xmx200m -Dcoherence.home=/opt/oracle/product/12.2.1.2.0/wlserver/../coherence -Dbea.home=/opt/oracle/product/12.2.1.2.0/wlserver/.. -DNodeManagerHome=/opt/oracle/config/domains/bi/nodemanager -DLogToStderr=false -DQuitEnabled=true -Dweblogic.RootDirectory=/opt/oracle/config/domains/bi -Doracle.security.jps.config=/opt/oracle/config/domains/bi/config/fmwconfig/jps-config-jse.xml -Dcommon.components.home=/opt/oracle/product/12.2.1.2.0/oracle_common -Dopss.version=12.2.1.2 -Dweblogic.RootDirectory=/opt/oracle/config/domains/bi -Doracle.bi.home.dir=/opt/oracle/product/12.2.1.2.0/bi -Doracle.bi.config.dir=/opt/oracle/config/domains/bi/config/fmwconfig/biconfig -Doracle.bi.environment.dir=/opt/oracle/config/domains/bi/config/fmwconfig/bienv -Doracle.bi.12c=true -Ddomain.home=/opt/oracle/config/domains/bi -Dfile.encoding=utf-8 -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -Djava.security.policy=/opt/oracle/product/12.2.1.2.0/wlserver/server/lib/weblogic.policy -Dweblogic.nodemanager.JavaHome=/usr/java/jdk1.8.0_101 weblogic.NodeManager -v
NMProcess: Aug 15, 2017 1:01:43 AM oracle.security.opss.internal.runtime.ServiceContextManagerImpl getContext
NMProcess: WARNING: Bootstrap services are used by OPSS internally and clients should never need to directly read/write bootstrap credentials. If required, use Wlst or configuration management interfaces.
NodeManager started

Reading domain...
/Servers/AdminServer/ListenPort=9500
Accessing admin server using URL t3://0cc73e26cd8f:9500
Starting AdminServer ...
**Admin Server Start Exception: Error occurred while performing nmStart : Error Starting server AdminServer : Received error message from Node Manager Server: [Server start command for WebLogic server 'AdminServer' failed due to: [Server failed to start up but Node Manager was not aware of the reason]. Please check Node Manager log and/or server 'AdminServer' log for detailed information.]. Please check Node Manager log for details.**
Use dumpStack() to view the full stacktrace :
Reading domain...
/Servers/AdminServer/ListenPort=9500
**Accessing admin server using URL t3://0cc73e26cd8f:9500
Requesting credentials ...
Enter Weblogic login details at prompt
Problem invoking WLST - Traceback (innermost last):**
  File "/opt/oracle/product/12.2.1.2.0/bi/modules/oracle.bi.sysman/scripts/start_servers.py", line 251, in ?
  File "/opt/oracle/product/12.2.1.2.0/bi/modules/oracle.bi.sysman/scripts/start_servers.py", line 220, in startAll
  File "/opt/oracle/product/12.2.1.2.0/bi/modules/oracle.bi.sysman/scripts/process_control.py", line 227, in connectAdminServer
  File "/opt/oracle/product/12.2.1.2.0/bi/modules/oracle.bi.sysman/scripts/process_control.py", line 181, in requestCredentialsAndConnectToAdminServer
  File "/opt/oracle/product/12.2.1.2.0/bi/modules/oracle.bi.sysman/scripts/process_control.py", line 98, in getCredentials
EOFError: raw_input()

Weblogic Username: #########################
Domain status; Using domainHome: /opt/oracle/config/domains/bi ...

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

<Aug 15, 2017 1:02:46 AM UTC> <Info> <Security> <BEA-090905> <Disabling the CryptoJ JCE Provider self-integrity check for better startup performance. To enable this check, specify -Dweblogic.security.allowCryptoJDefaultJCEVerification=true.>
<Aug 15, 2017 1:02:46 AM UTC> <Info> <Security> <BEA-090906> <Changing the default Random Number Generator in RSA CryptoJ from ECDRBG128 to HMACDRBG. To disable this change, specify -Dweblogic.security.allowCryptoJDefaultPRNG=true.>
<Aug 15, 2017 1:02:46 AM UTC> <Info> <Security> <BEA-090909> <Using the configured custom SSL Hostname Verifier implementation: weblogic.security.utils.SSLWLSHostnameVerifier$NullHostnameVerifier.>
/Servers/AdminServer/ListenPort=9500
Accessing admin server using URL t3://0cc73e26cd8f:9500
Start Admin Server connect Exception caught Error occurred while performing connect : Error getting the initial context. There is no server running at t3://0cc73e26cd8f:9500 : Failed to initialize JNDI context, tried 2 time or times totally, the interval of each time is 0ms.
t3://0cc73e26cd8f:9500: Destination 172.17.0.2, 9500 unreachable.; nested exception is:
	java.net.ConnectException: Connection refused; No available router to destination.; nested exception is:
	java.rmi.ConnectException: No available router to destination.
Use dumpStack() to view the full stacktrace :
Reading domain...
Error: runCmd() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/opt/oracle/product/12.2.1.2.0/bi/modules/oracle.bi.sysman/scripts/status_servers.py", line 29, in ?
  File "/opt/oracle/product/12.2.1.2.0/bi/modules/oracle.bi.sysman/scripts/process_control.py", line 581, in statusComponents
  File "/opt/oracle/product/12.2.1.2.0/bi/modules/oracle.bi.sysman/scripts/process_control.py", line 455, in outputComponentsStatus
  File "/opt/oracle/product/12.2.1.2.0/bi/modules/oracle.bi.sysman/scripts/process_control.py", line 243, in connectAdminServer
  File "/opt/oracle/product/12.2.1.2.0/bi/modules/oracle.bi.sysman/scripts/process_control.py", line 179, in requestCredentialsAndConnectToAdminServer
  File "/opt/oracle/product/12.2.1.2.0/bi/modules/oracle.bi.sysman/scripts/process_control.py", line 513, in getAdminServerUrl
  File "/tmp/WLSTOfflineIni4152367849953242456.py", line 127, in readDomain
  File "/tmp/WLSTOfflineIni4152367849953242456.py", line 19, in command
60713: Attempt to execute command "readDomain" in invalid state: Configuration
60713: Check the logs for more information.
 @com.oracle.cie.domain.script.jython.WLSTState.processCommand(WLSTState.java:211)
	at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
	at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2768)
	at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:701)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: 60713: Command execution failed.
60713: Attempt to execute command "readDomain" in invalid state: Configuration
60713: Check the logs for more information.
 @com.oracle.cie.domain.script.jython.WLSTState.processCommand(WLSTState.java:211)

**Comment by gianniceresa** [comment]
Standard OBIEE debugging: look at the logs. The message tells to look at NodeManager and AdminServer logs, if AdminServer is the one failing I would start from that log.

**Comment by manik-chopra** [comment]
Not an OBIEE person thus was looking for any insight. But i'll try and see what i can find. thanks.

**Comment by gianniceresa** [comment]
You do not have to mix things: Docker is one side but inside the container there is OBIEE running. So if OBIEE doesn't start (the AdminServer) you need to first get the real cause to see if it's an OBIEE or Docker issue. I'm using OBIEE in Docker for almost a year, with many containers and not had issues using the new image.

**Comment by manik-chopra** [comment]
I think I found the issue, During docker start it is expecting the DB credentials (BI_CONFIG_RCU_DBSTRING, BI_CONFIG_RCU_PWD, BI_CONFIG_RCU_USER etc.) that were passed during docker run to create the container. Do you know off a way to pass these during docker start?

I'm trying to avoid storing these values inside the container.

**Comment by gianniceresa** [comment]
You can't, that's not how Docker work and it isn't how the image expect things.
The RCU is created at the first execution, the settings are set on "docker create" or "docker run" (which is a mix of create + start).

You seem to have some particular needs and try to achieve them in your own way instead of using the tool how it has been designed. This image is a generic OBIEE setup, and works fine when used in the normal OBIEE way.
