### ISSUE TITLE
Oracle Analytics Server 6.4.0 fails to build image 

### ISSUE THREAD

**Issue by nndlovu11** [gianniceresa/docker-images#8]
0.236   inflating: /opt/oracle/install/tmp_wls/fmw_12.2.1.4.0_infrastructure.jar  
9.658   inflating: /opt/oracle/install/tmp_wls/fmw_12214_readme.html  
10.03 Launcher log file is /tmp/OraInstall2024-04-13_08-47-59PM/launcher2024-04-13_08-47-59PM.log.
10.10 Extracting the installer . . . . . . . Done
14.52 Checking if CPU speed is above 300 MHz.   Actual 2499.998 MHz    Passed
14.53 Checking swap space: must be greater than 512 MB.   Actual 0 MB    Failed <<<<
14.53 Checking if this platform requires a 64-bit JVM.   Actual 64    Passed (64-bit not required)
14.53 Checking temp space: must be greater than 300 MB.   Actual 194806 MB    Passed
14.53 
14.53 Some system prerequisite checks failed.
14.53 You must fulfill these requirements before continuing.
14.53 The log is located here: /tmp/OraInstall2024-04-13_08-47-59PM/launcher2024-04-13_08-47-59PM.log.

**Comment by gianniceresa** [comment]
_Checking swap space: must be greater than 512 MB. Actual 0 MB_
Common environments have swap space, the tool requires some and tests for it. There should be a parameter to skip all the checks, but you could also just add some swap space (even "fake" one in a file) to your environment.
